server:
  port: 8080

management:
  tracing:
    enabled: true

logging:
  level:
    fast:
      retire: debug

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: app_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
