server:
  port: 8080

logging:
  level:
    pl:
      kmlk: debug

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db?currentSchema=ft_dev
    username: app_user
    password: app_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
