<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pl.kmlk</groupId>
        <artifactId>fast-retire</artifactId>
        <version>0.0.4-SNAPSHOT</version>
    </parent>

    <artifactId>fast-retire-standalone</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>pl.kmlk</groupId>
            <artifactId>fast-retire-infrastructure</artifactId>
            <version>0.0.4-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>11.13.2</version>
                <configuration>
                    <url>jdbc:postgresql://192.168.88.22:5432/appdb?currentSchema=ft_dev</url>
                    <user>kamil</user>
                    <password>kamil1234</password>
                    <createSchemas>true</createSchemas>
                    <schemas>
                        <schema>ft_dev</schema>
                    </schemas>
                    <locations>
                        <location>filesystem:src/main/resources/db/migration</location>
                    </locations>
                </configuration>

                <dependencies>
                    <!-- WYMAGANE: plugin bazy PostgreSQL dla Flyway 11+ -->
                    <dependency>
                        <groupId>org.flywaydb</groupId>
                        <artifactId>flyway-database-postgresql</artifactId>
                        <version>11.13.2</version>
                    </dependency>
                    <!-- Sterownik JDBC -->
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.7.4</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>